name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: abcd
        env: 
          SECRET_FILE: ${{ secrets.SECRET_FILE }}
        run: |
            pwd
            touch /home/runner/work/test/test/out.json
            echo "SECRET_FILE" >> /home/runner/work/test/test/out.json
            cat /home/runner/work/test/test/out.json
